Update Why CachyOS? section
CachyOS/wiki pull request #54
Opened 2024-08-16 15:02 UTC by aarrayy

I think for now its way better with the new wording.

I also removed some things such as RT being labeled as a scheduler

Feel free to review and make a suggestion if needed

2024-08-16 15:16 UTC, 1Naim requested changes

2024-08-16 15:16 UTC, 1Naim commented on src/content/docs/cachyos_basic/why_cachyos.md
> +## What makes CachyOS not just another Arch based distro?
This line seems a bit out of place, maybe we can merge it with the bottom paragraph

2024-08-16 15:16 UTC, 1Naim commented on src/content/docs/cachyos_basic/why_cachyos.md
> +## What makes CachyOS not just another Arch based distro?
After moving the above sentence to the bottom paragraph, maybe we can just remove this subheading altogether. If removing this makes the below paragraph lose context, we can change the title of this page. What do you think?

2024-08-16 17:01 UTC, aarrayy commented on src/content/docs/cachyos_basic/why_cachyos.md
> +We offer a variety of [desktop environments](/installation/desktop_environments/), [boot managers](/installation/boot_managers/)
boot managers link should work after #53 is merged

2024-08-16 17:11 UTC, 1Naim requested changes

2024-08-16 17:11 UTC, 1Naim commented on src/content/docs/cachyos_basic/why_cachyos.md
> +For more information, check out [this](/cachyos_repositories/what_are_the_cachyos_repo) page for a more detailed explanation of the optimized repositories that we provide.
```suggestion
Check out [this](/cachyos_repositories/what_are_the_cachyos_repo) page for a more detailed explanation of the optimized repositories that we provide.
```

2024-08-16 17:20 UTC, aarrayy commented on src/content/docs/cachyos_basic/why_cachyos.md
> +For more information, check out [this](/cachyos_repositories/what_are_the_cachyos_repo) page for a more detailed explanation of the optimized repositories that we provide.
u sure?

2024-08-16 17:22 UTC, aarrayy commented on src/content/docs/cachyos_basic/why_cachyos.md
> +For more information, check out [this](/cachyos_repositories/what_are_the_cachyos_repo) page for a more detailed explanation of the optimized repositories that we provide.
nvm i see why xD

2024-08-16 17:23 UTC, 1Naim approved these changes
LGTM

2024-08-17 12:29 UTC, ptr1337 approved these changes

2024-08-17 12:29 UTC, merged