Fr translation 2
CachyOS/wiki pull request #60
Opened 2024-08-24 07:28 UTC by kensama31

Can you please review the work on my wiki fr page please

2024-08-24 12:46 UTC, 1Naim requested changes
This PR has a **LOT** of files that hasn't been translated yet. Please do not add these files to the PR if they have not been translated yet.

2024-08-24 12:46 UTC, 1Naim commented on src/content/docs/fr/cachyos_repositories/how_to_add_cachyos_repo.mdx
> +
This is still in english

2024-08-24 12:46 UTC, 1Naim commented on src/content/docs/fr/cachyos_repositories/other_optimization.md
> +
Remove this file if it hasn't been translated yet

2024-08-24 12:46 UTC, 1Naim commented on src/content/docs/fr/cachyos_repositories/what_are_the_cachyos_repo.md
> +https://lists.archlinux.org/pipermail/arch-general/2021-March/048739.html
same

2024-08-24 15:41 UTC, 1Naim approved these changes
LGTM from website POV. Someone please proofread these french translations :)

2025-08-05 22:07 UTC, Shendisx commented
Closing due to inactivity.

2025-08-05 22:07 UTC, closed without merging